on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'v**'

name: CI

jobs:
  jekyll-build:
    name: Build (jekyll gem)
    strategy:
      fail-fast: false
      matrix:
        jekyll-version: [ 3.9, 4.3 ]
        os: [ ubuntu-latest ]
        ruby-version: [ 3.1 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: false
      - name: Bundle Install (Jekyll ${{ matrix.jekyll-version }})
        run: bundle install
        env:
          BUNDLE_GEMFILE: fixtures/Gemfile-jekyll-${{ matrix.jekyll-version }}
      - name: Init Search
        run: bundle exec rake search:init
        env:
          BUNDLE_GEMFILE: fixtures/Gemfile-jekyll-${{ matrix.jekyll-version }}
      - name: Build Site
        run: bundle exec jekyll build
        env:
          BUNDLE_GEMFILE: fixtures/Gemfile-jekyll-${{ matrix.jekyll-version }}

  assets:
    name: Test CSS and JS
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
